name: 'Update wiki'
description: 'This action updates wiki repository with changes made in base repository'
inputs:
  path:  
    description: 'Location of wiki directory'
    required: true
    default: 'wiki'
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/update-wiki.sh 
      shell: bash
      env:       
        WIKI_DIR: ${{ inputs.path }}
        GH_TOKEN: ${{ inputs.token }}
branding:
  icon: book-open
  color: white 
